### ISSUE TITLE
multiple header is appearing with if.bind

### ISSUE THREAD

**Issue by webcat12345** [arabsight/aurelia-quill-plugin#3]
My project is aurelia-cli (webpack)

### Reproduce step

Component A: 
```
<template>
   <div>.... <quill-editor></quill-editor> ... </div>
</template>

```

Parent Component:
```
<component-a if.bind="show"></component-a>
<button click.delegate="show = !show">Show/Hide</button>
```

If I try Show/Hide button several times, then quill editor displays headers multiple time,
Looks like only last header is available for actions, if I try buttons from other headers, it does not work.

Screenshot attached:
![image](https://user-images.githubusercontent.com/19761422/53325617-90fa0680-3898-11e9-948a-cd8981e0766d.png)

### What we need
We may need something like a function to detach or reset the quill editor handler.

**Comment by webcat12345** [comment]
I am using this HOTFIX for now... this could help anybody who blocked by the same issue.

```
quill-editor {
      // TODO: HOTFIX - quill editor header is appearing multiple times, force hide them on the UI
      // TODO: submitted ticket: https://github.com/arabsight/aurelia-quill-plugin/issues/3
      .ql-toolbar {
        display: none;
        &:nth-last-child(2) {
          display: block;
        }
      }
    }
```

**Comment by arabsight** [comment]
it should be fixed now. Unfortunately Quill doesn't have a way to dispose the editor.

**Comment by webcat12345** [comment]
Thanks for the quick update!

**Comment by webcat12345** [comment]
Just installed `"_id": "aurelia-quill-plugin@0.1.5",` but issue still exists...

**Comment by webcat12345** [comment]
Sorry, all works.

**Comment by webcat12345** [comment]
This happened again with 0.1.6... :(
